require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

# 空メソッドの場合に、1行のスタイルにしない　NG例：def style1; end
Style/EmptyMethod:
  EnforcedStyle: expanded

# クラス内にクラスが定義されていないかチェック（無効）
Style/ClassAndModuleChildren:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# クラスやモジュール定義前に、それらの説明書きがあるかをチェック（無効）
Style/Documentation:
  Enabled: false

# 文字列に値が代入されて変わっていないかチェック（無効）
Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ContextWording:
  Enabled: false